
import { Country } from "./types";

export const countries: Country[] = [
  { code: "AF", name: "Afghanistan", blocked: false },
  { code: "AX", name: "Aland Islands", blocked: false },
  { code: "AL", name: "Albania", blocked: false },
  { code: "DZ", name: "Algeria", blocked: false },
  { code: "AS", name: "American Samoa", blocked: false },
  { code: "AD", name: "Andorra", blocked: false },
  { code: "AO", name: "Angola", blocked: false },
  { code: "AI", name: "Anguilla", blocked: false },
  { code: "AQ", name: "Antarctica", blocked: false },
  { code: "AG", name: "Antigua And Barbuda", blocked: false },
  { code: "AR", name: "Argentina", blocked: false },
  { code: "AM", name: "Armenia", blocked: false },
  { code: "AW", name: "Aruba", blocked: false },
  { code: "AU", name: "Australia", blocked: false },
  { code: "AT", name: "Austria", blocked: false },
  { code: "AZ", name: "Azerbaijan", blocked: false },
  { code: "BS", name: "Bahamas", blocked: false },
  { code: "BH", name: "Bahrain", blocked: false },
  { code: "BD", name: "Bangladesh", blocked: false },
  { code: "BB", name: "Barbados", blocked: false },
  { code: "BY", name: "Belarus", blocked: false },
  { code: "BE", name: "Belgium", blocked: false },
  { code: "BZ", name: "Belize", blocked: false },
  { code: "BJ", name: "Benin", blocked: false },
  { code: "BM", name: "Bermuda", blocked: false },
  { code: "BT", name: "Bhutan", blocked: false },
  { code: "BO", name: "Bolivia", blocked: false },
  { code: "BA", name: "Bosnia And Herzegovina", blocked: false },
  { code: "BW", name: "Botswana", blocked: false },
  { code: "BV", name: "Bouvet Island", blocked: false },
  { code: "BR", name: "Brazil", blocked: false },
  { code: "IO", name: "British Indian Ocean Territory", blocked: false },
  { code: "BN", name: "Brunei Darussalam", blocked: false },
  { code: "BG", name: "Bulgaria", blocked: false },
  { code: "BF", name: "Burkina Faso", blocked: false },
  { code: "BI", name: "Burundi", blocked: false },
  { code: "KH", name: "Cambodia", blocked: false },
  { code: "CM", name: "Cameroon", blocked: false },
  { code: "CA", name: "Canada", blocked: false },
  { code: "CV", name: "Cape Verde", blocked: false },
  { code: "KY", name: "Cayman Islands", blocked: false },
  { code: "CF", name: "Central African Republic", blocked: false },
  { code: "TD", name: "Chad", blocked: false },
  { code: "CL", name: "Chile", blocked: false },
  { code: "CN", name: "China", blocked: false },
  { code: "CX", name: "Christmas Island", blocked: false },
  { code: "CC", name: "Cocos (Keeling) Islands", blocked: false },
  { code: "CO", name: "Colombia", blocked: false },
  { code: "KM", name: "Comoros", blocked: false },
  { code: "CG", name: "Congo", blocked: false },
  { code: "CD", name: "Congo, Democratic Republic", blocked: false },
  { code: "CK", name: "Cook Islands", blocked: false },
  { code: "CR", name: "Costa Rica", blocked: false },
  { code: "CI", name: "Cote D'Ivoire", blocked: false },
  { code: "HR", name: "Croatia", blocked: false },
  { code: "CU", name: "Cuba", blocked: false },
  { code: "CY", name: "Cyprus", blocked: false },
  { code: "CZ", name: "Czech Republic", blocked: false },
  { code: "DK", name: "Denmark", blocked: false },
  { code: "DJ", name: "Djibouti", blocked: false },
  { code: "DM", name: "Dominica", blocked: false },
  { code: "DO", name: "Dominican Republic", blocked: false },
  { code: "EC", name: "Ecuador", blocked: false },
  { code: "EG", name: "Egypt", blocked: false },
  { code: "SV", name: "El Salvador", blocked: false },
  { code: "GQ", name: "Equatorial Guinea", blocked: false },
  { code: "ER", name: "Eritrea", blocked: false },
  { code: "EE", name: "Estonia", blocked: false },
  { code: "ET", name: "Ethiopia", blocked: false },
  { code: "FK", name: "Falkland Islands (Malvinas)", blocked: false },
  { code: "FO", name: "Faroe Islands", blocked: false },
  { code: "FJ", name: "Fiji", blocked: false },
  { code: "FI", name: "Finland", blocked: false },
  { code: "FR", name: "France", blocked: false },
  { code: "GF", name: "French Guiana", blocked: false },
  { code: "PF", name: "French Polynesia", blocked: false },
  { code: "TF", name: "French Southern Territories", blocked: false },
  { code: "GA", name: "Gabon", blocked: false },
  { code: "GM", name: "Gambia", blocked: false },
  { code: "GE", name: "Georgia", blocked: false },
  { code: "DE", name: "Germany", blocked: false },
  { code: "GH", name: "Ghana", blocked: false },
  { code: "GI", name: "Gibraltar", blocked: false },
  { code: "GR", name: "Greece", blocked: false },
  { code: "GL", name: "Greenland", blocked: false },
  { code: "GD", name: "Grenada", blocked: false },
  { code: "GP", name: "Guadeloupe", blocked: false },
  { code: "GU", name: "Guam", blocked: false },
  { code: "GT", name: "Guatemala", blocked: false },
  { code: "GG", name: "Guernsey", blocked: false },
  { code: "GN", name: "Guinea", blocked: false },
  { code: "GW", name: "Guinea-Bissau", blocked: false },
  { code: "GY", name: "Guyana", blocked: false },
  { code: "HT", name: "Haiti", blocked: false },
  { code: "HM", name: "Heard Island & Mcdonald Islands", blocked: false },
  { code: "VA", name: "Holy See (Vatican City State)", blocked: false },
  { code: "HN", name: "Honduras", blocked: false },
  { code: "HK", name: "Hong Kong", blocked: false },
  { code: "HU", name: "Hungary", blocked: false },
  { code: "IS", name: "Iceland", blocked: false },
  { code: "IN", name: "India", blocked: false },
  { code: "ID", name: "Indonesia", blocked: false },
  { code: "IR", name: "Iran, Islamic Republic Of", blocked: false },
  { code: "IQ", name: "Iraq", blocked: false },
  { code: "IE", name: "Ireland", blocked: false },
  { code: "IM", name: "Isle Of Man", blocked: false },
  { code: "IL", name: "Israel", blocked: false },
  { code: "IT", name: "Italy", blocked: false },
  { code: "JM", name: "Jamaica", blocked: false },
  { code: "JP", name: "Japan", blocked: false },
  { code: "JE", name: "Jersey", blocked: false },
  { code: "JO", name: "Jordan", blocked: false },
  { code: "KZ", name: "Kazakhstan", blocked: false },
  { code: "KE", name: "Kenya", blocked: false },
  { code: "KI", name: "Kiribati", blocked: false },
  { code: "KR", name: "Korea", blocked: false },
  { code: "KW", name: "Kuwait", blocked: false },
  { code: "KG", name: "Kyrgyzstan", blocked: false },
  { code: "LA", name: "Lao People's Democratic Republic", blocked: false },
  { code: "LV", name: "Latvia", blocked: false },
  { code: "LB", name: "Lebanon", blocked: false },
  { code: "LS", name: "Lesotho", blocked: false },
  { code: "LR", name: "Liberia", blocked: false },
  { code: "LY", name: "Libyan Arab Jamahiriya", blocked: false },
  { code: "LI", name: "Liechtenstein", blocked: false },
  { code: "LT", name: "Lithuania", blocked: false },
  { code: "LU", name: "Luxembourg", blocked: false },
  { code: "MO", name: "Macao", blocked: false },
  { code: "MK", name: "Macedonia", blocked: false },
  { code: "MG", name: "Madagascar", blocked: false },
  { code: "MW", name: "Malawi", blocked: false },
  { code: "MY", name: "Malaysia", blocked: false },
  { code: "MV", name: "Maldives", blocked: false },
  { code: "ML", name: "Mali", blocked: false },
  { code: "MT", name: "Malta", blocked: false },
  { code: "MH", name: "Marshall Islands", blocked: false },
  { code: "MQ", name: "Martinique", blocked: false },
  { code: "MR", name: "Mauritania", blocked: false },
  { code: "MU", name: "Mauritius", blocked: false },
  { code: "YT", name: "Mayotte", blocked: false },
  { code: "MX", name: "Mexico", blocked: false },
  { code: "FM", name: "Micronesia, Federated States Of", blocked: false },
  { code: "MD", name: "Moldova", blocked: false },
  { code: "MC", name: "Monaco", blocked: false },
  { code: "MN", name: "Mongolia", blocked: false },
  { code: "ME", name: "Montenegro", blocked: false },
  { code: "MS", name: "Montserrat", blocked: false },
  { code: "MA", name: "Morocco", blocked: false },
  { code: "MZ", name: "Mozambique", blocked: false },
  { code: "MM", name: "Myanmar", blocked: false },
  { code: "NA", name: "Namibia", blocked: false },
  { code: "NR", name: "Nauru", blocked: false },
  { code: "NP", name: "Nepal", blocked: false },
  { code: "NL", name: "Netherlands", blocked: false },
  { code: "AN", name: "Netherlands Antilles", blocked: false },
  { code: "NC", name: "New Caledonia", blocked: false },
  { code: "NZ", name: "New Zealand", blocked: false },
  { code: "NI", name: "Nicaragua", blocked: false },
  { code: "NE", name: "Niger", blocked: false },
  { code: "NG", name: "Nigeria", blocked: false },
  { code: "NU", name: "Niue", blocked: false },
  { code: "NF", name: "Norfolk Island", blocked: false },
  { code: "MP", name: "Northern Mariana Islands", blocked: false },
  { code: "NO", name: "Norway", blocked: false },
  { code: "OM", name: "Oman", blocked: false },
  { code: "PK", name: "Pakistan", blocked: false },
  { code: "PW", name: "Palau", blocked: false },
  { code: "PS", name: "Palestinian Territory, Occupied", blocked: false },
  { code: "PA", name: "Panama", blocked: false },
  { code: "PG", name: "Papua New Guinea", blocked: false },
  { code: "PY", name: "Paraguay", blocked: false },
  { code: "PE", name: "Peru", blocked: false },
  { code: "PH", name: "Philippines", blocked: false },
  { code: "PN", name: "Pitcairn", blocked: false },
  { code: "PL", name: "Poland", blocked: false },
  { code: "PT", name: "Portugal", blocked: false },
  { code: "PR", name: "Puerto Rico", blocked: false },
  { code: "QA", name: "Qatar", blocked: false },
  { code: "RE", name: "Reunion", blocked: false },
  { code: "RO", name: "Romania", blocked: false },
  { code: "RU", name: "Russian Federation", blocked: false },
  { code: "RW", name: "Rwanda", blocked: false },
  { code: "BL", name: "Saint Barthelemy", blocked: false },
  { code: "SH", name: "Saint Helena", blocked: false },
  { code: "KN", name: "Saint Kitts And Nevis", blocked: false },
  { code: "LC", name: "Saint Lucia", blocked: false },
  { code: "MF", name: "Saint Martin", blocked: false },
  { code: "PM", name: "Saint Pierre And Miquelon", blocked: false },
  { code: "VC", name: "Saint Vincent And Grenadines", blocked: false },
  { code: "WS", name: "Samoa", blocked: false },
  { code: "SM", name: "San Marino", blocked: false },
  { code: "ST", name: "Sao Tome And Principe", blocked: false },
  { code: "SA", name: "Saudi Arabia", blocked: false },
  { code: "SN", name: "Senegal", blocked: false },
  { code: "RS", name: "Serbia", blocked: false },
  { code: "SC", name: "Seychelles", blocked: false },
  { code: "SL", name: "Sierra Leone", blocked: false },
  { code: "SG", name: "Singapore", blocked: false },
  { code: "SK", name: "Slovakia", blocked: false },
  { code: "SI", name: "Slovenia", blocked: false },
  { code: "SB", name: "Solomon Islands", blocked: false },
  { code: "SO", name: "Somalia", blocked: false },
  { code: "ZA", name: "South Africa", blocked: false },
  { code: "GS", name: "South Georgia And Sandwich Isl.", blocked: false },
  { code: "ES", name: "Spain", blocked: false },
  { code: "LK", name: "Sri Lanka", blocked: false },
  { code: "SD", name: "Sudan", blocked: false },
  { code: "SR", name: "Suriname", blocked: false },
  { code: "SJ", name: "Svalbard And Jan Mayen", blocked: false },
  { code: "SZ", name: "Swaziland", blocked: false },
  { code: "SE", name: "Sweden", blocked: false },
  { code: "CH", name: "Switzerland", blocked: false },
  { code: "SY", name: "Syrian Arab Republic", blocked: false },
  { code: "TW", name: "Taiwan", blocked: false },
  { code: "TJ", name: "Tajikistan", blocked: false },
  { code: "TZ", name: "Tanzania", blocked: false },
  { code: "TH", name: "Thailand", blocked: false },
  { code: "TL", name: "Timor-Leste", blocked: false },
  { code: "TG", name: "Togo", blocked: false },
  { code: "TK", name: "Tokelau", blocked: false },
  { code: "TO", name: "Tonga", blocked: false },
  { code: "TT", name: "Trinidad And Tobago", blocked: false },
  { code: "TN", name: "Tunisia", blocked: false },
  { code: "TR", name: "Turkey", blocked: false },
  { code: "TM", name: "Turkmenistan", blocked: false },
  { code: "TC", name: "Turks And Caicos Islands", blocked: false },
  { code: "TV", name: "Tuvalu", blocked: false },
  { code: "UG", name: "Uganda", blocked: false },
  { code: "UA", name: "Ukraine", blocked: false },
  { code: "AE", name: "United Arab Emirates", blocked: false },
  { code: "GB", name: "United Kingdom", blocked: false },
  { code: "US", name: "United States", blocked: false },
  { code: "UM", name: "United States Outlying Islands", blocked: false },
  { code: "UY", name: "Uruguay", blocked: false },
  { code: "UZ", name: "Uzbekistan", blocked: false },
  { code: "VU", name: "Vanuatu", blocked: false },
  { code: "VE", name: "Venezuela", blocked: false },
  { code: "VN", name: "Vietnam", blocked: false },
  { code: "VG", name: "Virgin Islands, British", blocked: false },
  { code: "VI", name: "Virgin Islands, U.S.", blocked: false },
  { code: "WF", name: "Wallis And Futuna", blocked: false },
  { code: "EH", name: "Western Sahara", blocked: false },
  { code: "YE", name: "Yemen", blocked: false },
  { code: "ZM", name: "Zambia", blocked: false },
  { code: "ZW", name: "Zimbabwe", blocked: false },
];

export const languages = [
  { code: "es", name: "Spanish" },
  { code: "en", name: "English" },
  { code: "ru", name: "Russian" },
  { code: "pt", name: "Portuguese" },
  { code: "fr", name: "French" },
  { code: "it", name: "Italian" },
  { code: "mn", name: "Mandarin" },
  { code: "el", name: "Greek" },
];

export const timezones = [
  { code: "UTC", name: "UTC" },
  { code: "Europe/Amsterdam", name: "Amsterdam (CET/CEST)" },
  { code: "Europe/London", name: "London (GMT/BST)" },
  { code: "America/New_York", name: "New York (EST/EDT)" },
  { code: "America/Los_Angeles", name: "Los Angeles (PST/PDT)" },
  { code: "Asia/Tokyo", name: "Tokyo (JST)" },
  { code: "Australia/Sydney", name: "Sydney (AEST/AEDT)" },
];
